trigger:
- main

pool:
  vmImage: ubuntu-latest


jobs:
- job: Job1

  steps:
  - script: echo Hello, Eri!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: job2
  dependsOn: Job1

  steps:
    - script: echo Job2!
      displayName: 'Run a one-line script'

- job: job3
  dependsOn: Job1

  steps:
    - script: echo Job3!
      displayName: 'Run a one-line script'

- job: job4
  dependsOn:
  - Job2
  - Job3

  steps:
    - script: echo Job4!
      displayName: 'Run a one-line script'