trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: FirstJob
      steps:
      - bash: echo $(PipelineLevelVariable)
  
    - job: SecondJob
      steps:
      - bash: echo Build / Second Job

  - stage: DevDeploy
    dependsOn: Build
    variables:
      environment: DevDeploy
    jobs:
      - job: FirstJob
        steps:
        - bash: echo $(environment) / First Job
  
  - stage: QADeploy
    dependsOn: Build
    variables:
      environment: QADeploy
    jobs:
      - job: FirstJob
        steps:
        - bash: echo $(environment) / First Job
    
  - stage: ProdDeply
    dependsOn:
    - DevDeploy
    - QADeploy
    variables:
      environment: ProdDeply
    jobs:
      - job: FirstJob
        steps:
        - bash: echo $(environment) / First Job
