trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: FirstJob
      steps:
      - bash: echo Build / First Job
  
    - job: SecondJob
      steps:
      - bash: echo Build / Second Job

  - stage: DevDeploy
    dependsOn: Build
    jobs:
      - job: FirstJob
        steps:
        - bash: echo DevDeploy / First Job
  
  - stage: QADeploy
    dependsOn: Build
    jobs:
      - job: FirstJob
        steps:
        - bash: echo QADeploy / First Job
    
  - stage: ProdDeply
    dependsOn:
    - DevDeploy
    - QADeploy
    jobs:
      - job: FirstJob
        steps:
        - bash: echo ProdDeply / First Job
